spring:
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  datasource:
    url: jdbc:postgresql://localhost/cloudsurfer
    username: postgres
    password: postgres
  security:
    enabled: false
---
spring:
  profiles: aws
  security:
    enabled: true
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://auth.cloudsurfer.uk/auth/realms/cloud-surfer
          jwk-set-uri: https://auth.cloudsurfer.uk/auth/realms/cloud-surfer/protocol/openid-connect/certs